// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#include "ui.h"

void ui_control_screen_init(void)
{
    ui_control = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_button_create(ui_control);
    lv_obj_set_width(ui_Button5, 80);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 5);
    lv_obj_set_y(ui_Button5, 5);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "< 返回");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_control);
    lv_slider_set_range(ui_Slider1, -100, 100);
    lv_slider_set_mode(ui_Slider1, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 27);
    lv_obj_set_y(ui_Slider1, -34);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TabView2 = lv_tabview_create(ui_control);
    lv_tabview_set_tab_bar_size(ui_TabView2, 50);
    lv_obj_set_width(ui_TabView2, 308);
    lv_obj_set_height(ui_TabView2, 180);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 20);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView2), &ui_font_chinese,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "串口信息");

    ui_Panel9 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel9, 286);
    lv_obj_set_height(ui_Panel9, 107);
    lv_obj_set_x(ui_Panel9, -2);
    lv_obj_set_y(ui_Panel9, -2);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serialtext1 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_serialtext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialtext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialtext1, 0);
    lv_obj_set_y(ui_serialtext1, -35);
    lv_obj_set_align(ui_serialtext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serialtext1, "SerialSerialSerialSerialSerialSerialSerial");

    ui_serialtext2 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_serialtext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialtext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialtext2, 0);
    lv_obj_set_y(ui_serialtext2, -20);
    lv_obj_set_align(ui_serialtext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serialtext2, "SerialSerialSerialSerialSerialSerialSerial");

    ui_serialtext4 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_serialtext4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialtext4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialtext4, 0);
    lv_obj_set_y(ui_serialtext4, 10);
    lv_obj_set_align(ui_serialtext4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serialtext4, "SerialSerialSerialSerialSerialSerialSerial");

    ui_serialtext3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_serialtext3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialtext3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialtext3, 0);
    lv_obj_set_y(ui_serialtext3, -5);
    lv_obj_set_align(ui_serialtext3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serialtext3, "SerialSerialSerialSerialSerialSerialSerial");

    ui_serialtext5 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_serialtext5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialtext5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialtext5, 0);
    lv_obj_set_y(ui_serialtext5, 25);
    lv_obj_set_align(ui_serialtext5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serialtext5, "SerialSerialSerialSerialSerialSerialSerial");

    ui_serialtext6 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_serialtext6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialtext6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialtext6, 0);
    lv_obj_set_y(ui_serialtext6, 40);
    lv_obj_set_align(ui_serialtext6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serialtext6, "SerialSerialSerialSerialSerialSerialSerial");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "舵机");

    ui_Panel11 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel11, 100);
    lv_obj_set_height(ui_Panel11, 108);
    lv_obj_set_x(ui_Panel11, -103);
    lv_obj_set_y(ui_Panel11, -2);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Panel11);
    lv_obj_set_width(ui_Arc1, 64);
    lv_obj_set_height(ui_Arc1, 64);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, 12);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 360);
    lv_arc_set_value(ui_Arc1, 0);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_arc_set_mode(ui_Arc1, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_Arc1, 90);
    lv_obj_set_style_arc_width(ui_Arc1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -35);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "云台");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel10, 40);
    lv_obj_set_height(ui_Panel10, 108);
    lv_obj_set_x(ui_Panel10, -24);
    lv_obj_set_y(ui_Panel10, -2);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_button_create(ui_Panel10);
    lv_obj_set_width(ui_Button8, 25);
    lv_obj_set_height(ui_Button8, 25);
    lv_obj_set_x(ui_Button8, 0);
    lv_obj_set_y(ui_Button8, -11);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -1);
    lv_obj_set_y(ui_Label26, 0);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "^");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_Panel10);
    lv_obj_set_width(ui_Button9, 25);
    lv_obj_set_height(ui_Button9, 25);
    lv_obj_set_x(ui_Button9, 0);
    lv_obj_set_y(ui_Button9, 35);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "v");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -38);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "1级");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 12);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "180");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel12, 40);
    lv_obj_set_height(ui_Panel12, 108);
    lv_obj_set_x(ui_Panel12, 24);
    lv_obj_set_y(ui_Panel12, -2);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button10 = lv_button_create(ui_Panel12);
    lv_obj_set_width(ui_Button10, 25);
    lv_obj_set_height(ui_Button10, 25);
    lv_obj_set_x(ui_Button10, 0);
    lv_obj_set_y(ui_Button10, -11);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -1);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "^");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_button_create(ui_Panel12);
    lv_obj_set_width(ui_Button11, 25);
    lv_obj_set_height(ui_Button11, 25);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, 35);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "v");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -38);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "2级");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 12);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "180");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel13, 40);
    lv_obj_set_height(ui_Panel13, 108);
    lv_obj_set_x(ui_Panel13, 72);
    lv_obj_set_y(ui_Panel13, -2);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_button_create(ui_Panel13);
    lv_obj_set_width(ui_Button12, 25);
    lv_obj_set_height(ui_Button12, 25);
    lv_obj_set_x(ui_Button12, 0);
    lv_obj_set_y(ui_Button12, -11);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -1);
    lv_obj_set_y(ui_Label22, 0);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "^");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_button_create(ui_Panel13);
    lv_obj_set_width(ui_Button13, 25);
    lv_obj_set_height(ui_Button13, 25);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, 35);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "v");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, -38);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "3级");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, 12);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "180");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel14, 40);
    lv_obj_set_height(ui_Panel14, 108);
    lv_obj_set_x(ui_Panel14, 120);
    lv_obj_set_y(ui_Panel14, -2);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_button_create(ui_Panel14);
    lv_obj_set_width(ui_Button14, 25);
    lv_obj_set_height(ui_Button14, 25);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, -11);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -1);
    lv_obj_set_y(ui_Label28, 0);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "^");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_button_create(ui_Panel14);
    lv_obj_set_width(ui_Button15, 25);
    lv_obj_set_height(ui_Button15, 25);
    lv_obj_set_x(ui_Button15, 0);
    lv_obj_set_y(ui_Button15, 35);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "v");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 0);
    lv_obj_set_y(ui_Label30, -38);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "爪");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 0);
    lv_obj_set_y(ui_Label31, 12);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "180");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView2, "电机");

    ui_Button6 = lv_button_create(ui_control);
    lv_obj_set_width(ui_Button6, 137);
    lv_obj_set_height(ui_Button6, 40);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 5);
    lv_obj_set_align(ui_Button6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "停止");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_control);
    lv_obj_set_width(ui_Button7, 80);
    lv_obj_set_height(ui_Button7, 40);
    lv_obj_set_x(ui_Button7, -5);
    lv_obj_set_y(ui_Button7, 5);
    lv_obj_set_align(ui_Button7, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x0FC121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "刷新");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
