// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_startupScreen
void ui_startupScreen_screen_init(void);
lv_obj_t * ui_startupScreen;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label10;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Checkbox5;
void ui_event_Button29(lv_event_t * e);
lv_obj_t * ui_Button29;
lv_obj_t * ui_Label36;
// CUSTOM VARIABLES

// SCREEN: ui_initScreen
void ui_initScreen_screen_init(void);
lv_obj_t * ui_initScreen;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Checkbox4;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Checkbox2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Checkbox3;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label32;
// CUSTOM VARIABLES

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_plus;
lv_obj_t * ui_taskcode2;
lv_obj_t * ui_taskcode1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_debugtext1;
lv_obj_t * ui_debugtext2;
lv_obj_t * ui_debugtext3;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label13;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

// SCREEN: ui_controlScreen
void ui_controlScreen_screen_init(void);
lv_obj_t * ui_controlScreen;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_otherPage;
lv_obj_t * ui_Panel17;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Label46;
void ui_event_Button34(lv_event_t * e);
lv_obj_t * ui_Button34;
lv_obj_t * ui_Label47;
void ui_event_Button35(lv_event_t * e);
lv_obj_t * ui_Button35;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Label50;
lv_obj_t * ui_xtext;
lv_obj_t * ui_ytext;
lv_obj_t * ui_Label53;
lv_obj_t * ui_dxtext;
lv_obj_t * ui_Label52;
lv_obj_t * ui_dytext;
lv_obj_t * ui_rpiPage;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label40;
lv_obj_t * ui_modeText;
lv_obj_t * ui_data1Text;
lv_obj_t * ui_data2Text;
lv_obj_t * ui_colorText;
void ui_event_Button30(lv_event_t * e);
lv_obj_t * ui_Button30;
lv_obj_t * ui_Label41;
void ui_event_Button31(lv_event_t * e);
lv_obj_t * ui_Button31;
lv_obj_t * ui_Label42;
void ui_event_Button32(lv_event_t * e);
lv_obj_t * ui_Button32;
lv_obj_t * ui_Label43;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
lv_obj_t * ui_Label44;
lv_obj_t * ui_motorPage;
lv_obj_t * ui_Label1;
void ui_event_univx(lv_event_t * e);
lv_obj_t * ui_univx;
lv_obj_t * ui_Label3;
void ui_event_univy(lv_event_t * e);
lv_obj_t * ui_univy;
lv_obj_t * ui_Label4;
void ui_event_uniomega(lv_event_t * e);
lv_obj_t * ui_uniomega;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label7;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label8;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label14;
lv_obj_t * ui_servoPage;
lv_obj_t * ui_Panel11;
void ui_event_servo0Arc(lv_event_t * e);
lv_obj_t * ui_servo0Arc;
lv_obj_t * ui_servo0Text;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label33;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label35;
void ui_event_Button28(lv_event_t * e);
lv_obj_t * ui_Button28;
lv_obj_t * ui_Label21;
lv_obj_t * ui_temp0;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label23;
lv_obj_t * ui_servo1Text;
lv_obj_t * ui_temp1;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label16;
lv_obj_t * ui_servo2Text;
lv_obj_t * ui_temp2;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label25;
lv_obj_t * ui_servo3Text;
lv_obj_t * ui_temp3;
lv_obj_t * ui_Panel14;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label28;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_servoClawText;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label27;
lv_obj_t * ui_actionGroupList;
void ui_event_Button27(lv_event_t * e);
lv_obj_t * ui_Button27;
lv_obj_t * ui_Label31;
lv_obj_t * ui_hwt101Page;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_hwt101data;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label45;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label18;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label19;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_mainScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        startupFunc(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_initScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_initScreen_screen_init);
    }
}

void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_startupScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_startupScreen_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        stopAllServoAndMotor(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        restartFunc(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_controlScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_controlScreen_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LEDfunction(e);
    }
}

void ui_event_Button34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        caliPosButton1(e);
    }
}

void ui_event_Button35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        caliPosButton2(e);
    }
}

void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mode_0_button(e);
    }
}

void ui_event_Button31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mode_1_button(e);
    }
}

void ui_event_Button32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mode_2_button(e);
    }
}

void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mode_3_button(e);
    }
}

void ui_event_univx(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        uniCtrlChange(e);
    }
}

void ui_event_univy(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        uniCtrlChange(e);
    }
}

void ui_event_uniomega(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        uniCtrlChange(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uniCtrlToZero(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uniMoveButton(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uniSwerveButton(e);
    }
}

void ui_event_servo0Arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        servo0Adjust(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        servo0Left(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        servo0Right(e);
    }
}

void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        servo0CalibrationOfs(e);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        servoClawOpen(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        servoClawClose(e);
    }
}

void ui_event_Button27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        actionGroupStart(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hwt101zero(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pidSwitch(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        stopAllServoAndMotor(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refreshButton(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resumeMainSequence(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_startupScreen_screen_init();
    ui_initScreen_screen_init();
    ui_mainScreen_screen_init();
    ui_controlScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_startupScreen);
}
