// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#include "ui.h"

void ui_controlScreen_screen_init(void)
{
    ui_controlScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_controlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_button_create(ui_controlScreen);
    lv_obj_set_width(ui_Button5, 80);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 5);
    lv_obj_set_y(ui_Button5, 5);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "< 返回");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_controlScreen);
    lv_slider_set_range(ui_Slider1, -100, 100);
    lv_slider_set_mode(ui_Slider1, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 27);
    lv_obj_set_y(ui_Slider1, -34);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TabView2 = lv_tabview_create(ui_controlScreen);
    lv_tabview_set_tab_bar_size(ui_TabView2, 30);
    lv_obj_set_width(ui_TabView2, 308);
    lv_obj_set_height(ui_TabView2, 186);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 23);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView2), &ui_font_chinese,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otherPage = lv_tabview_add_tab(ui_TabView2, "其他");

    ui_Panel17 = lv_obj_create(ui_otherPage);
    lv_obj_set_width(ui_Panel17, 100);
    lv_obj_set_height(ui_Panel17, 50);
    lv_obj_set_x(ui_Panel17, -91);
    lv_obj_set_y(ui_Panel17, -40);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_Panel17);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 17);
    lv_obj_set_y(ui_Switch2, 0);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Label46 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, -25);
    lv_obj_set_y(ui_Label46, 0);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "LED");
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button34 = lv_button_create(ui_otherPage);
    lv_obj_set_width(ui_Button34, 60);
    lv_obj_set_height(ui_Button34, 50);
    lv_obj_set_x(ui_Button34, 20);
    lv_obj_set_y(ui_Button34, -40);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label47 = lv_label_create(ui_Button34);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "caliPos1");
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button35 = lv_button_create(ui_otherPage);
    lv_obj_set_width(ui_Button35, 60);
    lv_obj_set_height(ui_Button35, 50);
    lv_obj_set_x(ui_Button35, 98);
    lv_obj_set_y(ui_Button35, -40);
    lv_obj_set_align(ui_Button35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label48 = lv_label_create(ui_Button35);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "caliPos2");
    lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_otherPage);
    lv_obj_set_width(ui_Panel18, 268);
    lv_obj_set_height(ui_Panel18, 67);
    lv_obj_set_x(ui_Panel18, -7);
    lv_obj_set_y(ui_Panel18, 30);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label49 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -115);
    lv_obj_set_y(ui_Label49, -15);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "x:");

    ui_Label50 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -115);
    lv_obj_set_y(ui_Label50, 15);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "y:");

    ui_xtext = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_xtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xtext, -45);
    lv_obj_set_y(ui_xtext, -15);
    lv_obj_set_align(ui_xtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xtext, "0");

    ui_ytext = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_ytext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ytext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ytext, -45);
    lv_obj_set_y(ui_ytext, 15);
    lv_obj_set_align(ui_ytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ytext, "0");

    ui_Label53 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, 70);
    lv_obj_set_y(ui_Label53, -15);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "dx:");

    ui_dxtext = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_dxtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dxtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dxtext, 100);
    lv_obj_set_y(ui_dxtext, -15);
    lv_obj_set_align(ui_dxtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dxtext, "0");

    ui_Label52 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 70);
    lv_obj_set_y(ui_Label52, 15);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "dy:");

    ui_dytext = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_dytext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dytext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dytext, 100);
    lv_obj_set_y(ui_dytext, 15);
    lv_obj_set_align(ui_dytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dytext, "0");

    ui_rpiPage = lv_tabview_add_tab(ui_TabView2, "树莓派");

    ui_Panel9 = lv_obj_create(ui_rpiPage);
    lv_obj_set_width(ui_Panel9, 282);
    lv_obj_set_height(ui_Panel9, 136);
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, -3);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -100);
    lv_obj_set_y(ui_Label37, -40);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "模式:");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -104);
    lv_obj_set_y(ui_Label38, -13);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "数据1:");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -105);
    lv_obj_set_y(ui_Label39, 13);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "数据2:");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -100);
    lv_obj_set_y(ui_Label40, 40);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "颜色:");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_modeText = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_modeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_modeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_modeText, -30);
    lv_obj_set_y(ui_modeText, -40);
    lv_obj_set_align(ui_modeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_modeText, "mode");

    ui_data1Text = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_data1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_data1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_data1Text, -30);
    lv_obj_set_y(ui_data1Text, -13);
    lv_obj_set_align(ui_data1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_data1Text, "data1");

    ui_data2Text = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_data2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_data2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_data2Text, -30);
    lv_obj_set_y(ui_data2Text, 13);
    lv_obj_set_align(ui_data2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_data2Text, "data2");

    ui_colorText = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_colorText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_colorText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colorText, -30);
    lv_obj_set_y(ui_colorText, 40);
    lv_obj_set_align(ui_colorText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colorText, "color");
    lv_obj_set_style_text_font(ui_colorText, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Button30, 95);
    lv_obj_set_height(ui_Button30, 28);
    lv_obj_set_x(ui_Button30, 75);
    lv_obj_set_y(ui_Button30, -48);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button30, lv_color_hex(0x4EC35A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "待命");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Button31, 95);
    lv_obj_set_height(ui_Button31, 28);
    lv_obj_set_x(ui_Button31, 75);
    lv_obj_set_y(ui_Button31, -16);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "二维码识别");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button32 = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Button32, 95);
    lv_obj_set_height(ui_Button32, 28);
    lv_obj_set_x(ui_Button32, 75);
    lv_obj_set_y(ui_Button32, 16);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "圆识别定位");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Button33, 95);
    lv_obj_set_height(ui_Button33, 28);
    lv_obj_set_x(ui_Button33, 75);
    lv_obj_set_y(ui_Button33, 48);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "色环定位");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motorPage = lv_tabview_add_tab(ui_TabView2, "电机");

    ui_Label1 = lv_label_create(ui_motorPage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -125);
    lv_obj_set_y(ui_Label1, -55);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "vx");

    ui_univx = lv_slider_create(ui_motorPage);
    lv_slider_set_range(ui_univx, -100, 100);
    lv_slider_set_mode(ui_univx, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_univx, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_univx) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_univx, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_univx, 236);
    lv_obj_set_height(ui_univx, 15);
    lv_obj_set_x(ui_univx, 22);
    lv_obj_set_y(ui_univx, -55);
    lv_obj_set_align(ui_univx, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_univx, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_univx,
                                                                                            lv_obj_get_style_pad_right(ui_univx, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label3 = lv_label_create(ui_motorPage);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -125);
    lv_obj_set_y(ui_Label3, -15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "vy");

    ui_univy = lv_slider_create(ui_motorPage);
    lv_slider_set_range(ui_univy, -100, 100);
    lv_slider_set_mode(ui_univy, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_univy, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_univy) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_univy, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_univy, 236);
    lv_obj_set_height(ui_univy, 15);
    lv_obj_set_x(ui_univy, 22);
    lv_obj_set_y(ui_univy, -15);
    lv_obj_set_align(ui_univy, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_univy, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_univy,
                                                                                            lv_obj_get_style_pad_right(ui_univy, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label4 = lv_label_create(ui_motorPage);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -125);
    lv_obj_set_y(ui_Label4, 25);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "omega");

    ui_uniomega = lv_slider_create(ui_motorPage);
    lv_slider_set_range(ui_uniomega, -100, 100);
    lv_slider_set_mode(ui_uniomega, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_uniomega, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uniomega) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_uniomega, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_uniomega, 236);
    lv_obj_set_height(ui_uniomega, 15);
    lv_obj_set_x(ui_uniomega, 22);
    lv_obj_set_y(ui_uniomega, 25);
    lv_obj_set_align(ui_uniomega, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_uniomega, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_uniomega,
                                                                                               lv_obj_get_style_pad_right(ui_uniomega, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Button8 = lv_button_create(ui_motorPage);
    lv_obj_set_width(ui_Button8, 56);
    lv_obj_set_height(ui_Button8, 25);
    lv_obj_set_x(ui_Button8, 113);
    lv_obj_set_y(ui_Button8, 52);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "归零");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_button_create(ui_motorPage);
    lv_obj_set_width(ui_Button10, 75);
    lv_obj_set_height(ui_Button10, 25);
    lv_obj_set_x(ui_Button10, -90);
    lv_obj_set_y(ui_Button10, 52);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "uniMove");

    ui_Button11 = lv_button_create(ui_motorPage);
    lv_obj_set_width(ui_Button11, 80);
    lv_obj_set_height(ui_Button11, 25);
    lv_obj_set_x(ui_Button11, -3);
    lv_obj_set_y(ui_Button11, 52);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "uniSwerve");

    ui_servoPage = lv_tabview_add_tab(ui_TabView2, "舵机");

    ui_Panel11 = lv_obj_create(ui_servoPage);
    lv_obj_set_width(ui_Panel11, 100);
    lv_obj_set_height(ui_Panel11, 108);
    lv_obj_set_x(ui_Panel11, -103);
    lv_obj_set_y(ui_Panel11, -21);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_servo0Arc = lv_arc_create(ui_Panel11);
    lv_obj_set_width(ui_servo0Arc, 64);
    lv_obj_set_height(ui_servo0Arc, 64);
    lv_obj_set_x(ui_servo0Arc, 0);
    lv_obj_set_y(ui_servo0Arc, 12);
    lv_obj_set_align(ui_servo0Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_servo0Arc, 0, 4096);
    lv_arc_set_value(ui_servo0Arc, 2048);
    lv_arc_set_bg_angles(ui_servo0Arc, 0, 360);
    lv_arc_set_rotation(ui_servo0Arc, 180);
    lv_obj_set_style_arc_width(ui_servo0Arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_servo0Arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_servo0Text = lv_label_create(ui_servo0Arc);
    lv_obj_set_width(ui_servo0Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo0Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo0Text, 0);
    lv_obj_set_y(ui_servo0Text, -11);
    lv_obj_set_align(ui_servo0Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo0Text, "2048");

    ui_Button18 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_Button18, 25);
    lv_obj_set_height(ui_Button18, 25);
    lv_obj_set_x(ui_Button18, -32);
    lv_obj_set_y(ui_Button18, -36);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "<");

    ui_Button19 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_Button19, 25);
    lv_obj_set_height(ui_Button19, 25);
    lv_obj_set_x(ui_Button19, 32);
    lv_obj_set_y(ui_Button19, -36);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, ">");

    ui_Button28 = lv_button_create(ui_Panel11);
    lv_obj_set_width(ui_Button28, 33);
    lv_obj_set_height(ui_Button28, 25);
    lv_obj_set_x(ui_Button28, 0);
    lv_obj_set_y(ui_Button28, -36);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0x0ACDF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "云台");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp0 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_temp0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp0, 0);
    lv_obj_set_y(ui_temp0, 20);
    lv_obj_set_align(ui_temp0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp0, "25");

    ui_Panel10 = lv_obj_create(ui_servoPage);
    lv_obj_set_width(ui_Panel10, 40);
    lv_obj_set_height(ui_Panel10, 108);
    lv_obj_set_x(ui_Panel10, -24);
    lv_obj_set_y(ui_Panel10, -21);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -38);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "1级");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servo1Text = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_servo1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo1Text, 0);
    lv_obj_set_y(ui_servo1Text, -10);
    lv_obj_set_align(ui_servo1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo1Text, "2048");
    lv_obj_set_style_text_font(ui_servo1Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp1 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp1, 0);
    lv_obj_set_y(ui_temp1, 14);
    lv_obj_set_align(ui_temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp1, "25");

    ui_Panel12 = lv_obj_create(ui_servoPage);
    lv_obj_set_width(ui_Panel12, 40);
    lv_obj_set_height(ui_Panel12, 108);
    lv_obj_set_x(ui_Panel12, 24);
    lv_obj_set_y(ui_Panel12, -21);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -38);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "2级");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servo2Text = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_servo2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo2Text, 0);
    lv_obj_set_y(ui_servo2Text, -10);
    lv_obj_set_align(ui_servo2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo2Text, "2048");
    lv_obj_set_style_text_font(ui_servo2Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp2 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp2, 0);
    lv_obj_set_y(ui_temp2, 14);
    lv_obj_set_align(ui_temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp2, "25");

    ui_Panel13 = lv_obj_create(ui_servoPage);
    lv_obj_set_width(ui_Panel13, 40);
    lv_obj_set_height(ui_Panel13, 108);
    lv_obj_set_x(ui_Panel13, 72);
    lv_obj_set_y(ui_Panel13, -21);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, -38);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "3级");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servo3Text = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_servo3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo3Text, 0);
    lv_obj_set_y(ui_servo3Text, -10);
    lv_obj_set_align(ui_servo3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo3Text, "2048");
    lv_obj_set_style_text_font(ui_servo3Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp3 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_temp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp3, 0);
    lv_obj_set_y(ui_temp3, 14);
    lv_obj_set_align(ui_temp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp3, "25");

    ui_Panel14 = lv_obj_create(ui_servoPage);
    lv_obj_set_width(ui_Panel14, 40);
    lv_obj_set_height(ui_Panel14, 108);
    lv_obj_set_x(ui_Panel14, 120);
    lv_obj_set_y(ui_Panel14, -21);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_button_create(ui_Panel14);
    lv_obj_set_width(ui_Button14, 25);
    lv_obj_set_height(ui_Button14, 25);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, -11);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "开");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_button_create(ui_Panel14);
    lv_obj_set_width(ui_Button15, 25);
    lv_obj_set_height(ui_Button15, 25);
    lv_obj_set_x(ui_Button15, 0);
    lv_obj_set_y(ui_Button15, 35);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "合");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 0);
    lv_obj_set_y(ui_Label30, -38);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "爪");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servoClawText = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_servoClawText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servoClawText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servoClawText, 0);
    lv_obj_set_y(ui_servoClawText, 12);
    lv_obj_set_align(ui_servoClawText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servoClawText, "2048");
    lv_obj_set_style_text_font(ui_servoClawText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_servoPage);
    lv_obj_set_width(ui_Panel16, 293);
    lv_obj_set_height(ui_Panel16, 30);
    lv_obj_set_x(ui_Panel16, -7);
    lv_obj_set_y(ui_Panel16, 50);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -110);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "动作组");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actionGroupList = lv_dropdown_create(ui_Panel16);
    lv_dropdown_set_options(ui_actionGroupList,
                            "fold\nmiddle\nnormal\nscanQRcode\nturntableDetect\nturntableCatchRedToPlate\nturntableCatchGreenToPlate\nturntableCatchBlueToPlate\ngroundDetect\nplateCatchRedToGround\nplateCatchGreenToGround\nplateCatchBlueToGround\ngroundCatchRedToPlate\ngroundCatchGreenToPlate\ngroundCatchBlueToPlate\nplateCatchRedToRed\nplateCatchGreenToGreen\nplateCatchBlueToBlue");
    lv_obj_set_width(ui_actionGroupList, 150);
    lv_obj_set_height(ui_actionGroupList, 20);
    lv_obj_set_align(ui_actionGroupList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_actionGroupList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_pad_left(ui_actionGroupList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_actionGroupList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_actionGroupList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_actionGroupList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_button_create(ui_Panel16);
    lv_obj_set_width(ui_Button27, 50);
    lv_obj_set_height(ui_Button27, 20);
    lv_obj_set_x(ui_Button27, 110);
    lv_obj_set_y(ui_Button27, 0);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "执行");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hwt101Page = lv_tabview_add_tab(ui_TabView2, "陀螺仪");

    ui_Panel15 = lv_obj_create(ui_hwt101Page);
    lv_obj_set_width(ui_Panel15, 282);
    lv_obj_set_height(ui_Panel15, 110);
    lv_obj_set_x(ui_Panel15, 0);
    lv_obj_set_y(ui_Panel15, -3);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwt101data = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_hwt101data, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hwt101data, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hwt101data, -31);
    lv_obj_set_y(ui_hwt101data, -18);
    lv_obj_set_align(ui_hwt101data, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hwt101data, "-180.000°");
    lv_obj_set_style_text_font(ui_hwt101data, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_button_create(ui_Panel15);
    lv_obj_set_width(ui_Button17, 50);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, 108);
    lv_obj_set_y(ui_Button17, -18);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button17, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "置零");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 50);
    lv_obj_set_y(ui_Label45, 30);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "PID");
    lv_obj_set_style_text_font(ui_Label45, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel15);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 100);
    lv_obj_set_y(ui_Switch1, 30);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Button6 = lv_button_create(ui_controlScreen);
    lv_obj_set_width(ui_Button6, 65);
    lv_obj_set_height(ui_Button6, 40);
    lv_obj_set_x(ui_Button6, -35);
    lv_obj_set_y(ui_Button6, 5);
    lv_obj_set_align(ui_Button6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "停止");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_controlScreen);
    lv_obj_set_width(ui_Button7, 80);
    lv_obj_set_height(ui_Button7, 40);
    lv_obj_set_x(ui_Button7, -5);
    lv_obj_set_y(ui_Button7, 5);
    lv_obj_set_align(ui_Button7, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "刷新");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_controlScreen);
    lv_obj_set_width(ui_Button9, 65);
    lv_obj_set_height(ui_Button9, 40);
    lv_obj_set_x(ui_Button9, 35);
    lv_obj_set_y(ui_Button9, 5);
    lv_obj_set_align(ui_Button9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x0FC121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "恢复");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button35, ui_event_Button35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button32, ui_event_Button32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button33, ui_event_Button33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_univx, ui_event_univx, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_univy, ui_event_univy, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uniomega, ui_event_uniomega, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_servo0Arc, ui_event_servo0Arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
