// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startupFunc(lv_event_t * e);
void stopAllServoAndMotor(lv_event_t * e);
void restartFunc(lv_event_t * e);
void LEDfunction(lv_event_t * e);
void caliPosButton1(lv_event_t * e);
void caliPosButton2(lv_event_t * e);
void mode_0_button(lv_event_t * e);
void mode_1_button(lv_event_t * e);
void mode_2_button(lv_event_t * e);
void mode_3_button(lv_event_t * e);
void uniCtrlChange(lv_event_t * e);
void uniCtrlToZero(lv_event_t * e);
void uniMoveButton(lv_event_t * e);
void uniSwerveButton(lv_event_t * e);
void servo0Adjust(lv_event_t * e);
void servo0Left(lv_event_t * e);
void servo0Right(lv_event_t * e);
void servo0CalibrationOfs(lv_event_t * e);
void servoClawOpen(lv_event_t * e);
void servoClawClose(lv_event_t * e);
void actionGroupStart(lv_event_t * e);
void hwt101zero(lv_event_t * e);
void pidSwitch(lv_event_t * e);
void refreshButton(lv_event_t * e);
void resumeMainSequence(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
