// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#include "ui.h"

void ui_initScreen_screen_init(void)
{
    ui_initScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_initScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_initScreen);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 85);
    lv_obj_set_height(ui_Spinner1, 85);
    lv_obj_set_x(ui_Spinner1, 75);
    lv_obj_set_y(ui_Spinner1, 0);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Spinner1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "初始化");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_initScreen);
    lv_obj_set_width(ui_Panel1, 130);
    lv_obj_set_height(ui_Panel1, 36);
    lv_obj_set_x(ui_Panel1, -60);
    lv_obj_set_y(ui_Panel1, -60);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox4 = lv_checkbox_create(ui_Panel1);
    lv_checkbox_set_text(ui_Checkbox4, "树莓派4B");
    lv_obj_set_width(ui_Checkbox4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Checkbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Checkbox4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Checkbox4, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_initScreen);
    lv_obj_set_width(ui_Panel2, 130);
    lv_obj_set_height(ui_Panel2, 36);
    lv_obj_set_x(ui_Panel2, -60);
    lv_obj_set_y(ui_Panel2, -20);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox1 = lv_checkbox_create(ui_Panel2);
    lv_checkbox_set_text(ui_Checkbox1, "陀螺仪");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Checkbox1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Checkbox1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_initScreen);
    lv_obj_set_width(ui_Panel3, 130);
    lv_obj_set_height(ui_Panel3, 36);
    lv_obj_set_x(ui_Panel3, -60);
    lv_obj_set_y(ui_Panel3, 20);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox2 = lv_checkbox_create(ui_Panel3);
    lv_checkbox_set_text(ui_Checkbox2, "电机");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_LEFT_MID);
    lv_obj_add_state(ui_Checkbox2, LV_STATE_CHECKED | LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Checkbox2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Checkbox2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_initScreen);
    lv_obj_set_width(ui_Panel4, 130);
    lv_obj_set_height(ui_Panel4, 36);
    lv_obj_set_x(ui_Panel4, -60);
    lv_obj_set_y(ui_Panel4, 60);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox3 = lv_checkbox_create(ui_Panel4);
    lv_checkbox_set_text(ui_Checkbox3, "舵机");
    lv_obj_set_width(ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Checkbox3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Checkbox3, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_button_create(ui_initScreen);
    lv_obj_set_width(ui_Button16, 60);
    lv_obj_set_height(ui_Button16, 30);
    lv_obj_set_x(ui_Button16, -258);
    lv_obj_set_y(ui_Button16, -208);
    lv_obj_set_align(ui_Button16, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "返回");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);

}
