// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_initSCreen
void ui_initSCreen_screen_init(void);
lv_obj_t * ui_initSCreen;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Checkbox4;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Checkbox2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Checkbox3;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label32;
// CUSTOM VARIABLES


// SCREEN: ui_startupScreen
void ui_startupScreen_screen_init(void);
lv_obj_t * ui_startupScreen;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label10;
// CUSTOM VARIABLES


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_plus;
lv_obj_t * ui_taskcode2;
lv_obj_t * ui_taskcode1;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_debugtext1;
lv_obj_t * ui_debugtext2;
lv_obj_t * ui_debugtext3;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label13;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label12;
// CUSTOM VARIABLES


// SCREEN: ui_control
void ui_control_screen_init(void);
lv_obj_t * ui_control;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_serialtext1;
lv_obj_t * ui_serialtext2;
lv_obj_t * ui_serialtext4;
lv_obj_t * ui_serialtext3;
lv_obj_t * ui_serialtext5;
lv_obj_t * ui_serialtext6;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_startupScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_startupScreen_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_startupScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_startupScreen_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_control_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_initSCreen_screen_init();
    ui_startupScreen_screen_init();
    ui_mainScreen_screen_init();
    ui_control_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_initSCreen);
}
