// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: EIC_LogisBot

#ifndef _EIC_LOGISBOT_UI_H
#define _EIC_LOGISBOT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_initSCreen
void ui_initSCreen_screen_init(void);
extern lv_obj_t * ui_initSCreen;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Checkbox3;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label32;
// CUSTOM VARIABLES

// SCREEN: ui_startupScreen
void ui_startupScreen_screen_init(void);
extern lv_obj_t * ui_startupScreen;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_plus;
extern lv_obj_t * ui_taskcode2;
extern lv_obj_t * ui_taskcode1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_debugtext1;
extern lv_obj_t * ui_debugtext2;
extern lv_obj_t * ui_debugtext3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label13;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

// SCREEN: ui_control
void ui_control_screen_init(void);
extern lv_obj_t * ui_control;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_serialtext1;
extern lv_obj_t * ui_serialtext2;
extern lv_obj_t * ui_serialtext4;
extern lv_obj_t * ui_serialtext3;
extern lv_obj_t * ui_serialtext5;
extern lv_obj_t * ui_serialtext6;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_taskcode);
LV_FONT_DECLARE(ui_font_bigchinese);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
